### PR TITLE
Bh/extend eslint config prettier

### PR DESCRIPTION
**Pull request by distrill**
extend prettier eslint config as well as airbnb

### CODE REVIEW

**Comment by gburtini** [comment]
did you test this?

**Comment by distrill** [comment]
I did, it worked in my current project

**Review by jakeorr — APPROVED** [review]
Nice, LGTM

**Comment by distrill** [comment]
it also didn't change anything. the rule in question was already configured in our eslint rules and my project just had an out of date version of this package. but we might as well keep this change as we've discussed it before

**Pull request merged**
